// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf3cFpXz0TgkVE7WnuIP-NwEB6hNYqgmk',
    appId: '1:528337686569:web:84b077f01c7b81d4ed8c38',
    messagingSenderId: '528337686569',
    projectId: 'geladeiraprojeto',
    authDomain: 'geladeiraprojeto.firebaseapp.com',
    databaseURL: 'https://geladeiraprojeto-default-rtdb.firebaseio.com',
    storageBucket: 'geladeiraprojeto.appspot.com',
    measurementId: 'G-4EB09BBHB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByf2eiPkIKKQbG4O1ZY3rNnlV-0WT1SCc',
    appId: '1:528337686569:android:c3e67ecd7e243e6ced8c38',
    messagingSenderId: '528337686569',
    projectId: 'geladeiraprojeto',
    databaseURL: 'https://geladeiraprojeto-default-rtdb.firebaseio.com',
    storageBucket: 'geladeiraprojeto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7ftQuhRx_TfJ27S3s-6J69hVoibj8jI',
    appId: '1:528337686569:ios:4d5ba93d3db98b8ded8c38',
    messagingSenderId: '528337686569',
    projectId: 'geladeiraprojeto',
    databaseURL: 'https://geladeiraprojeto-default-rtdb.firebaseio.com',
    storageBucket: 'geladeiraprojeto.appspot.com',
    iosBundleId: 'com.example.projetoGeladeiraNovo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv7ftQuhRx_TfJ27S3s-6J69hVoibj8jI',
    appId: '1:528337686569:ios:4d5ba93d3db98b8ded8c38',
    messagingSenderId: '528337686569',
    projectId: 'geladeiraprojeto',
    databaseURL: 'https://geladeiraprojeto-default-rtdb.firebaseio.com',
    storageBucket: 'geladeiraprojeto.appspot.com',
    iosBundleId: 'com.example.projetoGeladeiraNovo',
  );
}
